---
Description: DO NOT DELETE STACK! Core VPC that all resources are based on

Resources:
  # Core VPC
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: core-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: core-igw

  IgwAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

  # Core MySQL
  MySql:
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
        - !Ref MySqlSecurityGroup
      DBInstanceIdentifier: core-mysql
      AllocatedStorage: "20"
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: "{{resolve:ssm:/core/mysql/user/master/username}}"
      MasterUserPassword: "{{resolve:ssm-secure:/core/mysql/user/master/password}}"
      AutoMinorVersionUpgrade: true
      DBSubnetGroupName: core-mysql-subnet-group
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot

  MySqlSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: core-mysql-security-group
      GroupDescription: Core MySQL Database Security Group
      VpcId: !ImportValue Core-Vpc

  MySqlSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Core MySQL Subnet Group
      DBSubnetGroupName: core-mysql-subnet-group
      SubnetIds:
        - !Ref MySqlSubnet1
        - !Ref MySqlSubnet2
  MySqlSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue Core-Vpc
      CidrBlock: 10.0.1.0/28
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs { Ref: "AWS::Region" }]
      Tags: [{ Key: Name, Value: CoreResources/MySql/Subnet0 }]

  MySqlSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue Core-Vpc
      CidrBlock: 10.0.1.16/28
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs { Ref: "AWS::Region" }]
      Tags: [{ Key: Name, Value: CoreResources/MySql/Subnet1 }]

Outputs:
  Vpc:
    Description: Core VPC ID
    Value: !Ref Vpc
    Export:
      Name: Core-Vpc
  Igw:
    Value: !GetAtt InternetGateway.InternetGatewayId
    Export:
      Name: Core-InternetGateway
