pipeline {
    agent {
        label 'deployer-slave-amazon-linux'
    }
    
    options {
        timeout(time: 30, unit: 'MINUTES')
    }

    stages {
        stage('Update Core VPC Resources'){
            steps{
                dir('core-vpc'){
                    sh 'aws cloudformation update-stack --region eu-west-2 --stack-name CoreVpc --capabilities CAPABILITY_NAMED_IAM --template-body file://cloudformation.yml --tags Key=service,Value=core-vpc'
                    sh 'aws cloudformation wait stack-update-complete --region eu-west-2 --stack-name CoreVpc'
                }
            }
        }
    }
}
