pipeline {
    agent {
        label 'deployer-slave-amazon-linux'
    }
    
    options {
        timeout(time: 90, unit: 'MINUTES')
    }

    stages {
        stage('Install CDK Packages'){
            steps{
                dir('core-resources/cdk'){ sh 'npm install'}
            }
        }

        stage('Wait Until Stack is Ready to Deploy'){
            sh(script: 'aws cloudformation wait stack-update-complete --region eu-west-2 --stack-name CoreResources', returnStatus: true)
        }
       
        stage('CDK Deploy'){
            steps{
                dir('core-resources/cdk'){ sh 'npm run cdk-deploy'}
            }
        }
    }
}
