pipeline {
    agent {
        label 'deployer-slave-amazon-linux'
    }
    
    options {
        timeout(time: 150, unit: 'MINUTES')
        timestamps ()
    }

    stages {
        stage('Install CDK Packages'){
            steps{
                dir('core-resources/cdk'){ sh 'npm install'}
            }
        }

        stage('Wait for Stack Ready'){
            steps{
                sh(script: 'aws cloudformation wait stack-update-complete --region eu-west-2 --stack-name CoreResources', returnStatus: true)
            }
        }
       
        stage('CDK Deploy'){
            steps{
                dir('core-resources/cdk'){ sh 'npm run cdk-deploy'}
            }
        }
    }    
    post { 
        always { 
            cleanWs()
        }
    }
}
